### ISSUE TITLE
merger calculator bug

### ISSUE THREAD

**Issue by mshteyn** [colindean/wilkinsburg_pittsburgh_merger_analysis#3]
Colin, the tool you created to estimate tax changes given a wilkinsburg merger with the city is nice contribution. I found a bug in the Total Yearly Tax output. Playing around with a couple of different input combos causes a bug in which the Total Yearly Tax row stays permanently in the "more" category (red color), even if the Total Yearly Tax is not actually more than before merger. In other words, the number is off by the right amount, but in the wrong direction. This bug seems to occur once numbers in the "Total Yearly Tax" row switch from the "less"(green) to "more"(red) category for the first time given a unique input combination. After that happens, regardless of how the input numbers are changed, the output for Total Yearly Tax stays "more"(red). 

See below: Where it says  	"$1,925.00 more", it should be reading " 	$1,925.00 less"

![image](https://user-images.githubusercontent.com/5659756/124400039-26b5c400-dce5-11eb-81d8-8b0000dceb3c.png)

Also just a word of advice: it could be good either to boldface the "Total Yearly Tax" row, or otherwise place it as the first row of the outputted table. This is a good way to guide the eye toward the most relevant number. Otherwise, it's easy to get a misleading first impression.

Anyway, thanks again for putting this together.
-m

**Comment by colindean** [comment]
Thanks for the compliment and the report. I've fixed the bug and implemented the suggestion in commit 58e4594.
