### ISSUE TITLE
Separate Wilkinsburg EIT and Wilkinsburg SD EIT

### ISSUE THREAD

**Issue by colindean** [colindean/wilkinsburg_pittsburgh_merger_analysis#5]
I learned today that Wilkinsburg residents' 1% EIT is actually 0.5% from the borough and 0.5% from the school district. The calculator and graph currently assume this is just 1% together. I want correct representation of the problem in source, so I need to break it down like I did for Pittsburgh.

**This does not affect the math of the calculator output** just the "show your work" that is the source code.

Research point: https://munstats.pa.gov/Public/FindLocalTax.aspx

**Comment by peplin** [comment]
Thanks for putting this together! I also didn't know the EIT was split like this. I think this correct actually does effect the calculator's results. The "school district merger only" EIT value is double counting school taxes:

```
results.set('sch-eit', w_eit(income) + p_sch_eit(income));
```

and the "no school district merger" was not counting that the 0.5% Wilkinsburg school EIT would remain.

I took a stab at a fix in #6.

**Comment by colindean** [comment]
Thanks, @peplin! 

#6 fixed this in the calculator but I need to make that change in the graphs code.
