### ISSUE TITLE
Consider dropping "muni annexation but no-school-merger" scenario since it's impossible under current law

### ISSUE THREAD

**Issue by vbuffry** [colindean/wilkinsburg_pittsburgh_merger_analysis#9]
Great work here making an objective, 'third-party' calculator for residents to assess for themselves what their financial picture will look like with a merger! I geeked out on how much more detail you get here than other calculators.

Since the creation of the calculator, state law has revealed that due to the type of school districts 'merging', the annexation of the borough would _automatically_ include the school district. In other words, there is no scenario in which the borough would be merged but not the school district. 

Here is the state law in question. Pittsburgh Public Schools is a so-called 'First Class' district: https://govt.westlaw.com/pac/Document/NB00F7040342F11DA8A989F4EECDB8638?viewType=FullText&originationContext=documenttoc&transitionType=CategoryPageItem&contextData=(sc.Default)

However, if the borough votes to remain independent, the WSD School Board could vote in an entirely separate process to merge the remaining elementary programs with PPS while the rest of the borough remains distinct. In that scenario, school property tax goes down, income taxes go up, and borough taxes stay the same.

Vanessa Buffry

**Comment by colindean** [comment]
Thanks for providing feedback!

I acknowledge this here, citing the same section of law:

https://github.com/colindean/wilkinsburg_pittsburgh_merger_analysis/blob/b04ad5f12b6fae01040e056a035dd648baa3bbc2/calculator.html#L170-L180

(this is the raw HTML of the page; it's in the Scenario Descriptions section)

I've contemplated dropping the "no school merger" scenario entirely from the graphs. I could make it clearer that the school district merger is unavoidable should the annexation be approved by referendum.  Reading over this again, this is a pretty strong nudge to make me go in that direction when I have time to do so. Thank you!

**Comment by colindean** [comment]
Thank you for nudging me on this. It's live shortly.

**Comment by vbuffry** [comment]
Hey no problem, I loved that I could get in touch and take advantage of the
moment to complement your civic energy and cool calculator. Glad you're my
neighbor. Cheers and happy Thanksgiving!
